# Generated by Django 4.1 on 2022-09-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('UID', models.AutoField(primary_key=True, serialize=False)),
                ('Text', models.TextField()),
                ('link', models.TextField()),
                ('Date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Eligility_Conditions',
            fields=[
                ('UID', models.AutoField(primary_key=True, serialize=False)),
                ('Field', models.CharField(max_length=255)),
                ('Category', models.CharField(max_length=255)),
                ('Age_min', models.IntegerField()),
                ('Age_max', models.IntegerField()),
                ('Qualification', models.CharField(max_length=255)),
                ('Qualification_Percentage', models.CharField(max_length=255)),
                ('Health', models.IntegerField()),
                ('Chest_Expansion', models.IntegerField()),
                ('Without_glass', models.CharField(max_length=255)),
                ('With_glass', models.CharField(max_length=255)),
                ('Color', models.CharField(max_length=255)),
                ('remarks', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'Eligility_Conditions',
            },
        ),
        migrations.CreateModel(
            name='Eligility_Conditions_PF_SP',
            fields=[
                ('UID', models.AutoField(primary_key=True, serialize=False)),
                ('Field', models.CharField(max_length=255)),
                ('Entry', models.CharField(max_length=255)),
                ('Age', models.CharField(max_length=255)),
                ('Education', models.CharField(max_length=255)),
                ('Height', models.CharField(max_length=255)),
                ('weight', models.IntegerField()),
                ('Chest', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('UID', models.AutoField(primary_key=True, serialize=False)),
                ('Text', models.TextField()),
                ('link', models.TextField()),
                ('Date', models.DateField(auto_now_add=True)),
                ('from_date', models.DateField()),
                ('end_date', models.DateField()),
                ('SubCategory', models.CharField(choices=[('army', 'army'), ('navy', 'navy'), ('airforce', 'Inter'), ('Air-force', 'Air-Force'), ('paramilitary', 'paramilitary'), ('other', 'other')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ipModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('ip', 'time')},
            },
        ),
    ]
