# Generated by Django 4.1 on 2022-09-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_notification_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='SubCategory',
            field=models.CharField(choices=[('army', 'army'), ('navy', 'navy'), ('airforce', 'airforce'), ('paramilitary', 'paramilitary'), ('other', 'other')], max_length=255),
        ),
    ]
