# Generated by Django 4.1 on 2022-09-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_results_delete_selected_candidate_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrer',
            fields=[
                ('UID', models.AutoField(primary_key=True, serialize=False)),
                ('Text', models.TextField()),
                ('link', models.TextField()),
                ('Date', models.DateField(auto_now_add=True)),
                ('from_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
