# Generated by Django 4.1 on 2022-09-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_carrer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eligility_conditions',
            name='Chest_Expansion',
            field=models.CharField(max_length=255),
        ),
    ]
